export const STUDENT = {
  STUDENT_ADD: "STUDENT_ADD",
  STUDENT_DELETE: "STUDENT_DELETE",
};

export const USER = {
  USER_ADD: "USER_ADD",
  USER_DELETE: "USER_DELETE",
};

export const SANPHAM = {
  SANPHAM_ADD: "SANPHAM_ADD",
  SANPHAM_DELETE: "SANPHAM_DELETE",
};
