export const SCREEN_URL = {
  HOME: '/',
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  PROFILE: '/profile',
  DETAILS: '/details/:urlPath/:productId',
  CART: '/cart',
  CHECKOUT: '/checkout',
  ADMIN_HOME: '/admin',
  ADMIN_LOGIN: '/admin/login',
  ADMIN_REGISTER: '/admin/register',
  ADMIN_USERS: '/admin/users',
  ADMIN_CREATE_USER: '/admin/create-user',
  ADMIN_EDIT_USER: '/admin/users/:userId',
  ADMIN_DETAIL_USER: '/admin/users/details/:userId',
  ADMIN_PRODUCT: '/admin/product',
  ADMIN_CREATE_PRODUCT: '/admin/create-product',
  ADMIN_EDIT_PRODUCT: '/admin/product/:productId',
  ADMIN_ACCOUNT: '/admin/account',
  ADMIN_SETTINGS: '/admin/settings',
  TODO_LIST: '/todo-list',
  CONTACT: '/contact',
};
